### ISSUE TITLE
How can I write arduino byte() in HAL

### ISSUE THREAD

**Issue by tanimun** [THiNK-Limited/LoRa-HAL#1]
void setConf(int addh, int addl, int ch, int netId){

	loraMode(2);
	HAL_Delay(200);
	byte*buffer;
	HAL_UART_Transmit(&huart2,(byte) 192);
	HAL_UART_Transmit(&huart2,(byte) 00);
	HAL_UART_Transmit(&huart2,(byte) 07);
	HAL_UART_Transmit(&huart2,(addh));
	HAL_UART_Transmit(&huart2,(addl));
	HAL_UART_Transmit(&huart2,(byte) netId);
	HAL_UART_Transmit(&huart2,(byte) 103);  //2.4kbps
	HAL_UART_Transmit(&huart2,(byte) 00); // 0 for 30dbm, 01 for 27dbm
	HAL_UART_Transmit(&huart2,(byte) ch);
	HAL_UART_Transmit(&huart2,(byte) 67); //Fixed Transmission
	HAL_Delay(100);

}

**Comment by pkchowdhury** [comment]
typedef uint8_t byte;
void CharToByte(char* chars, byte* bytes, int count){
    
    for(unsigned int i = 0; i < count; i++){
        bytes[i] = (byte)chars[i];
        Serial2_write(bytes[i]);
    }
}
